### PR TITLE
Adds VG roundstart music

### PR DESCRIPTION
**Pull request by TaxMaster**
Adds various roundstart .oggs from VG.

Includes such songs like
 Carmen Miranda's Ghost
 Chris Hadfield's rendition of Space Oddity
 Starman
 Space Asshole

among other songs.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
I need playable links of these.

**Comment by TaxMaster** [comment]
https://mega.nz/#!NkkxFLQa!630VXPCqnP_4PvunJmTf1QFLd-muYT40FSIvOevHHF4

Also contains a txt file containing where the music is from (to the best of my investigative ability).

**Comment by TalkingCactus** [comment]
Use https://clyp.it/ so I don't need to download it.

**Comment by TalkingCactus** [comment]
And revert whatever you did to the .gitignore file.

**Comment by TaxMaster** [comment]
[Tracking Beacon - Half Life 2](https://clyp.it/ncuqzvg5)
[Carmen Miranda's Ghost - Leslie Fish](https://clyp.it/cldo3mrm)
[Century 21 March - Barry Gray](https://clyp.it/23a5uqst)
[Dawson's Christian - Duane Elms (Version by Vic Tyler)](https://clyp.it/3oxdgmdn)
[Theme of GTA 4: Ballad of Gay Tony](https://clyp.it/21f153nl)
[Grunty Industries (Inside the Factory) - Banjo Tooie](https://clyp.it/td0mlwxq)
[Space Oddity - David Bowie (Version by MikeCothren using Moonbase Alpha's Text2Speech)](https://clyp.it/oo0ipjv0)
[Space Asshole - Chris Remo](https://clyp.it/h3dmmpww)
[Space Oddity - David Bowie (Version by Chris Hadfield)](https://clyp.it/icunjge5)
[Starman - David Bowie](https://clyp.it/zmsxepbr)
[Torvus - Metroid Prime 2 Echos (I can't pinpoint if this is a remix or not)](https://clyp.it/fns2la2u)

Also I just grabbed the original .gitignore file from citadel-station-13/citadel-station-13/master and over-wrote the one in the PR.

**Pull request merged**
