### PR TITLE
FUCK NIGGERS AND FUCK JANNIES

### PR DESCRIPTION
**Pull request by EgoSumStultus**
## About The Pull Request
Ports the Blind quirk [from /tg/](https://github.com/tgstation/tgstation/pull/41130)

## Why It's Good For The Game
It is an oddly fun challenge, one of my favorite quirks. At first glance, it would not seem interesting -- but attempting to navigate through the station with nothing but your memory of the map is actually a very cool et fun experience.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Make sure to role restick it to only cargo techs, assistants and other non-important roles

**Comment by EgoSumStultus** [comment]
The trait blacklisting system is not yet implemented.

**Comment by Trilbyspaceclone** [comment]
fair

**Comment by Trilbyspaceclone** [comment]
Conflicting in files @EgoSumStultus

**Comment by EgoSumStultus** [comment]
i fixed the conflicts you dumb fucking BOT what do you WANT from me

**Comment by Trilbyspaceclone** [comment]
@EgoSumStultus Well you see, Map diff was unable to run do to the conflicting files, thus it failed... If you could try again to fix the conflicting files, such as replacing the files again. It should fix itself. The bot *is* working as intended from what I have seen...

**Comment by davidchan13** [comment]
-4 a bit much for a traits that can be side stepped with eye implants.

**Comment by Drowzyleaf** [comment]
@davidchan13 Pretty sure there's no way to cure it. Eye implants would do nothing.

**Comment by EgoSumStultus** [comment]
Drowzyleaf is correct. There is no way to restore your sight, ever. It is permanent blindness. 
And in my opinion, no amount of trait points could make up for lost vision. It's intended to be a challenge, not just a bad trait that gives points.

**Comment by nik707** [comment]
>Conflicting files
>code/datums/traits/negative.dm
>icons/mob/eyes.dmi
>icons/obj/clothing/glasses.dmi

**Pull request closed without merging**
