### PR TITLE
A small fix

### PR DESCRIPTION
**Pull request by TaxMaster**
Fixes up my plasmagun code so that the projectiles have an impact_effect.

### CODE REVIEW

**Comment by TaxMaster** [comment]
Advanced power armor and Krotchy
ce9fce5fa728f8ab0816cd7c38b9ff5e

Krotchy's lines
6eed82e1ecc76e4ac2d3b4caac21fe59

**Comment by TalkingCactus** [comment]
Why are you adding this?

**Comment by TaxMaster** [comment]
At first I just wanted to fix the plasma gun sprites not leaving an impact on the mobs it hits after I found out during a thunder-dome battle. After fixing said issue, I though 'Ya know, it feels kinda wrong in some way to just release this little PR' so I added two mostly useless things to it.

This whole PR felt strange when I was coding it, I dunno why.

**Comment by Poojawa** [comment]
it's okay to do small PRs. I did a single tab fix of your own code. :P

**Comment by TalkingCactus** [comment]
Just strip away the fallout crap and the doll.

**Comment by LetterJay** [comment]
@TaxMaster Is this good to merge?

**Comment by TaxMaster** [comment]
Yep.

**Comment by TalkingCactus** [comment]
Fix the title and description.

**Comment by TaxMaster** [comment]
Also done.

**Pull request merged**
