### PR TITLE
Adds Rollerbeds to MediHounds

### PR DESCRIPTION
**Pull request by CameronWoof**
:cl: CameronWoof
add: Medihounds now have rollerbeds for non-vore patient transport
/:cl:

[why]: Because it's better than nothing and I think that's hard to disagree with. Quick win buff to a famously struggling module.

### CODE REVIEW

**Comment by Poojawa** [comment]
"Because it's better than nothing"

They already have patient transport.

**Comment by CameronWoof** [comment]
They have patient transport that is very robust but only usable on less than half of the people playing. This gives them an alternative to dragging vore-disabled patients bleeding through the hallways, which I think we can all agree is an upgrade.

**Comment by Poojawa** [comment]
blimey, I wonder why that is.

**Comment by CameronWoof** [comment]
Please keep feedback related to this PR, not a settled issue from half a year ago. Denying the addition of a rollerbed because of your personal feelings on consent is petty.

**Review by deathride58 — APPROVED** [review]

**Comment by deathride58** [comment]
Roller beds will be vastly inferior to the sleeper once the sleeper is made normie-compatible.

**Comment by CameronWoof** [comment]
We can probably safely remove them at that point. Or leave them for **dual patient transport weewoo**

**Review by silicons — APPROVED** [review]

**Pull request merged**
