### PR TITLE
[READY] Ghost Cafe Overhaul (Fixed)

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request
Ghost cafe has been updated, and the kinks from the previous PR have been corrected. The cafe has been rebuilt from the ground up with a new layout, pacifism areas, and the construction/war zones from the previous PR. There's also a chemistry lab that's relatively isolated and covered in invisible, indestructible holofans to keep any "accidents" contained.
Reference Images:
[https://i.imgur.com/1llef5I.png](url)
[https://i.imgur.com/h2nAIhH.png](url)
[https://i.imgur.com/gJfs0Fv.png](url)

## Why It's Good For The Game
Gives players who decided to observe roundstart a playground if things are boring, along with giving dead players something more fun since not everyone will wanna just hang out in a vibe zone. The construction area has a lot of room for people to do big projects with, especially if admins wanna give people engine stuff to practice with or just build a big nightclub or something.

This is not a replacement for the actual game, all it is is a way for dead players primarily to have some fun they can do in addition to having options for just vibing.

## Changelog
:cl:
add: added pacifism areas that will apply pacifism to anyone entering them, and remove the trait if you leave them. Returning to a pacifism area will apply pacifism again.
tweak: overhauled the ghost cafe to be a multi-purpose zone for people to experiment, build, practice certain things, or just chill. Or ERP, I guess.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Glad you left the ability to crash the server in thats my favorite feature 🥴

**Comment by ForrestWick** [comment]
> Glad you left the ability to crash the server in thats my favorite feature 🥴 

Mind elaborating?

**Comment by MrJWhit** [comment]
1. You can hack the protolathe to produce an RPD, and use that to break atmos.
2. You can throw plasma from the upgraded chem dispensers.
3. You can make n2o from the chem room, and throw it to create mistakes.
4. You can spawncamp by shooting through turnstyles at people.
5. You can put chemicals in the pool from the chem room.
6. If you set the chem room on fire, it will overheat the area, there are no tiny fans.
7. If you explode a microwave on rugs, it will expose the tile, thereby letting you build machines, or wrench them down, where you shouldn't be able to.
8. You can bring guns to the hotel and shoot around in an unapproved area.
9. You can build windows in the construction area, drag them to the station, to then wrench down.
10. Personal lockers just don't work
11. You can place racks next to the spawn area, and for some reason, you can't climb over them. This bricks anyone from joining because they don't have tools to get themselves out.

**Comment by ForrestWick** [comment]
Too many issues I can't replicate on local. I'm just abandoning this project altogether

**Pull request closed without merging**
