### PR TITLE
fetish content nukie maids

### PR DESCRIPTION
**Pull request by Ludox235**
## About The Pull Request
image

## Why It's Good For The Game
You see this is good for the game because

## Changelog
:cl:
add: combat maid nukies
add: combat evening gloves (only used by nukies)
add: combat maid uniform (only used by nukies)
/:cl:

### CODE REVIEW

**Comment by Ludox235** [comment]
> 
> 
> while this is true, it doesn't hurt to give some defense just so people don't complain and ahelp that their teammate op was useless due to wearing a maid outfit

Alright sure. But should I make it a subtype of the maid costume in costume.dm or should I make it an item in syndicate.dm?

**Comment by timothyteakettle** [comment]
subtype in syndicate.dm because that's where people will look if they try finding it

**Comment by Arturlang** [comment]
What if maid armor was good armor!?!??!

**Comment by Ludox235** [comment]
> 
> 
> What if maid armor was good armor!?!??!

WEAR YOUR HARDSUIT ASSHOLE :((((

**Comment by Ludox235** [comment]
I FORGOT THE HEADBANDS IM A DISGRACE WTF

**Comment by lolman360** [comment]
how the fuck is your 22 line pr failing travis

**Comment by Arturlang** [comment]
@Ludox235 https://i.imgur.com/I9mMoQI.png

**Comment by Arturlang** [comment]
https://cdn.discordapp.com/attachments/161574200581029888/747248764300820510/syndimaid.dmi
@ForrestWick made it

**Comment by Ludox235** [comment]
> 
> 
> how the fuck is your 22 line pr failing travis

I'm like 99% sure it's because my fork is 1000 commits behind and behind the travis fix or whatever

**Comment by Ludox235** [comment]
> 
> 
> @Ludox235
> I9mMoQI

Thanks I hate it

**Comment by Arturlang** [comment]
Its epic isnt it

**Comment by Arturlang** [comment]
I suggest adding a way to click on the hardsuit with the maid outfit, making that monstrocity

**Comment by Ludox235** [comment]
> 
> 
> I suggest adding a way to click on the hardsuit with the maid outfit, making that monstrocity

Yeah okay sure I just kinda fucking don't know how to code so it'll be a magnificent learning experience.

**Comment by Ludox235** [comment]
@Arturlang 
There is no sprites for the combat mode of the maids so I'm gonna _try_. 
Keyword:
 ### _**TRY**_

To make them. Unless @ForrestWick is willing to make the combat versions though it kinda bothers me asking them since it's already generous enough of them to have sprited the EVA versions despite this being a dumb meme pr :)

**Comment by ForrestWick** [comment]
Just copy paste the headdress part onto the combat mode sprite

**Comment by Ludox235** [comment]
> 
> 
> Just copy paste the headdress part onto the combat mode sprite

yeah i'm doing that rn

**Comment by optimumtact** [comment]
mind if we port this?

**Comment by Ludox235** [comment]
> 
> 
> mind if we port this?

Screenshot_1361

On another note I managed to get it so you can make the syndicate maid hardsuit by slapping a maid costume on a normal hardsuit. But I have absolutely no fucking idea how to stop the subtypes of hardsuit/syndi from doing so too, since the maid hardsuit (and elite, owl, and bla blabla) are subtypes you can strap a costume on them too but it makes no sense considering 
 they're already a maid hardsuit or they're a owl/elite hardsuit so uuh yeah I'm gonna keep searching

**Comment by Ludox235** [comment]
I broke everything xd gonna do another pr

**Comment by optimumtact** [comment]
Is that a yes or a no?

**Comment by Arturlang** [comment]
Dont spam PRs, just change branches if one is too fucked.

**Comment by Ludox235** [comment]
> 
> 
> Is that a yes or a no?

Yeah okay sure

**Pull request closed without merging**
