### PR TITLE
using cult comms no longer whispers your message in normal speak

### PR DESCRIPTION
**Pull request by Ludox235**
Makes talking in cult communion no longer whisper your message in common

:cl:
Cult communion is now anonymous to nearby non-cultist
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
Why is this good for the game?

**Comment by Ludox235** [comment]
Because using super cult edgy spells to talk on some kind of blood channel and having it not be a unintelligible mess to non-cultists is completely illogical
also prevents HOS hearing 
"O'bidai nabo'ra ses'ma! [NAME] [NAME] [CULT LEADER NAME] plz help"

if you want I could try making it so it says whatever you said after the "o'bidai ect" in nar-sian

**Comment by kevinz000** [comment]
I don't see this as beneficial to cult tbh. It's strong enough.

**Comment by deathride58** [comment]
holy shit i havent seen a pr with so many thumbs downs here since part 1 of my combat rework

**Comment by deathride58** [comment]
also im 90% sure you can speak in narsian over cult comms by simply switching your language in the language menu

**Comment by MimicFaux** [comment]
> also im 90% sure you can speak in narsian over cult comms by simply switching your language in the language menu

Most of cult communications where secrecy is relevant happens by someone briefly breaking line of sight with their coworkers, hitting enter and then dipping back into sight to avoid suspicion. No one is going to be futzing about with language menus for practicality.

**Comment by deathride58** [comment]
A good alternative then would be to make it so that whispering in cult communication automatically makes you speak narsian by default, instead of it being handled manually

**Comment by kevinz000** [comment]
cult can use some buffing for anti late game magrifles/etc but this isn't the way sorry

**Pull request closed without merging**
