### PR TITLE
[READY] Old Station: Expansion

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request
Old Station has had a makeover. Featuring several new areas, new spawners, new gear, different enemies, and changes to existing areas, the Charlie Station ghost role ruin will likely prove to be a neat experience to new and old players of the role. 

New areas include: Dorms, chapel, vault, cargo, medical, atmos, a destroyed mining shuttle with hostile hivebots inside and a reward for the miner specifically.

Changes include: transit tubes replaced with bridges, medical fixed up, atmos partially fixed up, hivebot ship changed to a xenobio lab and AI chamber, with a vault as well, security area has two tiny jail cells for flavor, retro lasers have been var-edited to do a bit more damage and have more shots in face of the xenomorphs, while still looking like the normal retro laser guns, the armor vest is now the half life armor vest, the degrading helmet is a riot helmet, the budget insuls are replaced with proper insuls with a different name and description. There are now two voidsuits and a mining hardsuit for the miner to go after.

New enemies: Xenomorphs replace the hivebots as the primary antagonist of the delta station RND wing. You'll face drones, hunters, sentinels, and even a queen in this section. They won't be able to get onto Charlie itself, and there's a 25% chance you and your fellow survivors will get a partially functioning Ripley as well to face them with! The Hivebots have taken over the Beta Station area, mostly atmos and medical. The medkit in medical will no longer be a simple snatch and grab, as you will need to dodge or kill the hivebots to get them.

New spawns: In addition to all this, four new spawns have been added to the ruin. in addition to an engineer, officer, and scientist, there will now be a doctor, a miner, a staff assistant, and a chaplain that you can play as. The doctor spawns with scrubs and a medkit, the miner has the old purple overalls, the assistant has budget insuls and a staff assistant jumpsuit (courtesy of @Hatterhat ), and the chaplain gets their normal jumpsuit, an armament beacon, a bible, and a nullrod when they spawn (these items do not appear until the chaplain is selected and spawns in, and odds are there won't be anyone who's space tiding fast enough to find Charlie during wiz or cult and bring them back to the station).

## Why It's Good For The Game
Gives the players in old station more room to play around in and explore, different experiences for returning players, and more spawns so one guy can't just die and take the spawn two more times to cuck other people out of it (more spawns won't stop this issue, but it'll mitigate it). The new roles open roleplay potential as well.

## Changelog
:cl:
add: Added new areas to old station, revising some existing areas as well.
tweak: made some small QOL changes such as giving old station proper insuls, a better laser gun, better armor, and new enemies.
spellcheck: One of the fluff papers said "he captain" when it should've said "the captain", this has been rectified.
/:cl:

### CODE REVIEW

**Comment by Sishen1542** [comment]
Downvoting since I believe we don't need a second nullrod in an easily meta-able ghost role.

**Comment by ForrestWick** [comment]
> Downvoting since I believe we don't need a second nullrod in an easily meta-able ghost role.

The nullrod doesn't appear unless the charlie station chaplain spawns

**Comment by Sishen1542** [comment]
> > Downvoting since I believe we don't need a second nullrod in an easily meta-able ghost role.
> 
> The nullrod doesn't appear unless the charlie station chaplain spawns

as in you can just respawn as someone more capable of fighting the magic threat, yes

**Comment by kappa-sama** [comment]
> Downvoting since I believe we don't need a second nullrod in an easily meta-able ghost role.

imagine being concerned about balance lol

**Comment by necromanceranne** [comment]
If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?

You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.

**Comment by ForrestWick** [comment]
> If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?
> 
> You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.

Or anyone with access to the console really. As long as someone has id console access they can spam chaplain slots

**Comment by Sishen1542** [comment]
> If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?
> 
> You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.



> > If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?
> > You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.
> 
> Or anyone with access to the console really. As long as someone has id console access they can spam chaplain slots

you say this but you are wrong

**Comment by ForrestWick** [comment]
> > If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?
> > 
> > You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.
> 
> 
> 
> > > If more chaplains spawn, they will always carry additional null rods if they're a late join chaplain after another chaplain joined the round. What's your point?
> > > You quite literally can have an entire crusade of magic immune losers turn up in a given round if the HoP is canny enough about it.
> > 
> > Or anyone with access to the console really. As long as someone has id console access they can spam chaplain slots
> 
> you say this but you are wrong 
> 

An existing chaplain needs to be on station for late join ones to spawn with a rod

**Comment by Sishen1542** [comment]
now you say this

alright ill remove the nullrod spawn from new chaps

**Comment by kappa-sama** [comment]
pr summary: adding extra laser guns, armor, antimagic, and a .357 reskin with spare speedloader in exchange for nerfing all of the mobs to be melee except for 1, thus allowing anyone to easily steamroll the super powerful ghost ruin even faster and get better rewards (a 60 damage revolver with 14 shots).

**Comment by kappa-sama** [comment]
revamped my comment: after further discussion i have come to realize that the revolver in the space ruin is actually a direct upgrade to the .357 revolver lol

**Comment by ForrestWick** [comment]
Something went wrong, I'll have to redo this from scratch

**Pull request closed without merging**
