### PR TITLE
all of my posts are serious and i am a threat to this repo

### PR DESCRIPTION
**Pull request by buffyuwu**
## About The Pull Request

toggleable smite for admins to make players confirm every movement choice

## Why It's Good For The Game

ezgif-3-658e9433830f

## Changelog
:cl:
add: movement based admin smite
/:cl:

image

### CODE REVIEW

**Comment by DeltaFire15** [comment]
While this would seem very funny to have, I don't think having a alert / sleep hooked into *Move()* is a good idea.

**Comment by buffyuwu** [comment]
> While this would seem very funny to have, I don't think having a alert / sleep hooked into _Move()_ is a good idea.

i am a threat

**Comment by DeltaFire15** [comment]
> i am a threat

Yes.

**Comment by buffyuwu** [comment]
ok this made me laugh for like 5 minutes anyway

**Comment by dzahlus** [comment]
wow why did you close this
wouldve been unironically based

**Pull request closed without merging**
